apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgB6IAFvRTITIHjk1zQ2vnyOXIOH76VmBbN1xBA7hSoViaZinjv2yM/b1VpRYEOtfNXWamTG/lvV8sKXrDU3VVdOTQnQyDiOr/1fAjabnoecomHng5AmKxhsNnMAbpid0bf88hpS4Aplut23pN2ApKNg/NtYqZ1AbRez0C0VjsujcctQvBOMpEGTdhCe3Ba3sMKLLDjBT242sF8QgzkKQLks1K9p88AijLQJl2Y+kS1+k9JQFoULyNLF/698v5UE58TNeMnjbg+tV+tGVxn6Qe+aSeo0oAjb3WiUawIHDjrzg3tGjqUKIqdI/8MSXvWhRtvNSwmMfGIjY5/qyN/D/tJn+oU+MyHk8Dfi8yRhFIMB3/lrCRN6t1QvhUolGRu1+1do+I0ctvYMYuNsGj8nS9t9HgY2Cqy0ErPiT72Hzu2wJLHMbTqFCRUEA2bMjEAMMMTfSpdXkVCIpIJVeleTWh+1jlPL3xPncB7rYHvLychs4yIpOtC/+mh01h17JWng2CFu1fEknPeQbvUvFHc/mbTANmXYDFuU/dkFN29Pjsm4q3BzbMfgyXLttx0/y479b6E+wPF51yGscM9K5sN/bWgnyZptj+1hST0JgzaMgu95rchmsfBPqrLdiN5fvZ0hyEganFMZhku9rn+hyoQftGopRRzex6TGkV3ujz2YrcXpd3DDqG1R6JzTcRlrzm0nT+NixnP/wd80MEslXpd9/cNabvURwzdeT5PNxzOLbRPgrcOXwcVAK3C26MQcauYczqrkSV+/JYaRDoOm0TQoPX/MA9hidxWlziYdha2zDEfif2dQ4gujkWUQXrYNdzBXK9dNXMHpWWs+Kz+qXYsSYPPgBc16wkw=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: crossplane-system

